# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Zomba
                                 A QGIS plugin
 zombaland management system
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-05-04
        git sha              : $Format:%H$
        copyright            : (C) 2019 by chanco
        email                : madamiss@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import psycopg2 as psycopg2
from PyQt5 import QtSql,QtGui
from qgis.core import QgsProject as qp, QgsFeature as qf, QgsFeatureRequest
from qgis.utils import iface
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QMessageBox, QTableView, QWidget, QListWidgetItem
from PyQt5.QtSql import *
from PyQt5.uic import loadUi

from .developer import Developer



# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .zomba_module_dialog import ZombaDialog, CustomeUI, LoginPanel, Tabs
import os.path


class Zomba:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Zomba_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Zomba_LMS')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Zomba', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/zomba_module/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Files'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Zomba_LMS'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ZombaDialog()
            self.loginPAnel = LoginPanel()
            self.matabu = Tabs()

        self.matabu.mainLeftList.itemSelectionChanged.connect(self.selectionChanged)
        self.matabu.filterList.textChanged.connect(self.filterListOnType)
        self.loginPAnel.login.clicked.connect(self.handle_login)

        self.selection()
        self.matabu.add_btn.clicked.connect(self.add_btn_handler)
        self.database = self.connectToDb()
        query = """SELECT plot_name,category, feature, st_area(geom) as area FROM plot;"""
        print(query)
        recordList = self.executeQuery(self.database, query)
        self.populateLeftList(recordList)
        self.available_plot_numbers()
        self.developers()
        #runmethod
        self.dlg.setCentralWidget(self.loginPAnel)
        self.dlg.show()
        # Run the dialog event loop
        result = self.matabu.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def selectionChanged(self):
        self.getSelectedFeature()

    def getSelectedFeature(self):
        row =  self.matabu.mainLeftList.currentRow()
        item = self.matabu.mainLeftList.item(row)
        self.matabu.selectedFeature.setText(item.text())
        self.populate_details(item.text())

    def connectToDb(self):
        db = QSqlDatabase('QPSQL')
        if db.isValid():
            db.setHostName('localhost')
            db.setDatabaseName('zomba_malawi')
            db.setUserName('postgres')
            db.setPassword('12345678')
            db.setPort(5432)
            print('connected')
        else:
            print('failed to connect')
        return db

    def executeQuery(self,dbase,query):
        recordList = []
        if dbase.open():
            myQuery = dbase.exec_(query)
            while myQuery.next():
                recordList.append(myQuery.record())
        return recordList

    def populateLeftList(self, records):
        self.matabu.mainLeftList.addItems(x.value("plot_name") for x in records)

    def populate_details(self, name):
        query = """SELECT plot_name,category, feature, st_area(geom) as area FROM plot WHERE plot_name = '"""+self.addQuote(name)+"';"

        '''select st_area(geom) as area , can also be rounded , readable area formated with commas 
        implemented method as a message'''
        print(query)
        after = self.executeQuery(self.database,query)[0]
        print(after.value("plot_name"))
        self.matabu.wikipedia.setText(str(after.value("category")))
        self.matabu.name_en.setText(self.format_area(after.value("area")))
        self.format_area(1234567.98)
        #self.matabu.name_es.setText(after.value("name_es"))
        self.matabu.geom.setText(str(after.value("area")))
        #self.matabu.gps_code.setText(after.value("gps_code"))

    def addQuote(self, name):
        if name.find("'")>=0:
            return name[:name.find("'")]+"'"+name[name.find("'"):]
        return name

    def filterListOnType(self):
        filter_text =  self.matabu.filterList.text().lower()
        #row = self.matabu.mainLeftList.currentRow()
        for it in range(self.matabu.mainLeftList.count()):
            item = self.matabu.mainLeftList.item(it)
            if filter_text in item.text().lower():
                self.matabu.mainLeftList.setRowHidden(it, False)
            else:
                self.matabu.mainLeftList.setRowHidden(it, True)

    def add_btn_handler(self):
        y = self.matabu.plot_combo.currentText()
        pn = y[:y.find(' ')]
        fname = self.matabu.fname.text()
        lname = self.matabu.lname.text()
        amt = self.matabu.amount.text()

        query_str = "INSERT INTO developer(fname,lname,plot_no) VALUES('"+fname+"','"+lname+"',"+pn+");"
        self.database.exec(query_str)
        #this is the way to go
        connection = self.connection()
        cursor = connection.cursor()
        latestAddedDeveloperQuery = """
            select fname, lname, plot_name, st_area(geom), date_offered area 
            from plot natural join developer where 
            developer.id in(select max(id) from developer);
            """
        if len(self.database.lastError().databaseText()) == 0:
            #print(self.database.lastError().text())
            self.showdialog("Successfully added")
            cursor.execute(latestAddedDeveloperQuery)
            self.viewDevelopersDetails(cursor.fetchone())
        else:
            print("insert not done bhobo")
            self.showdialog("Developer not added review the details")

    def showdialog(self,feedback):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)

        msg.setText(feedback)
        msg.setInformativeText(" ")
        msg.setWindowTitle("Add dev")
        msg.setDetailedText("")
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        #msg.buttonClicked.connect(self.msgbtn)

        retval = msg.exec_()
        print("value of pressed message box button:", retval)

    def msgbtn(i):
        #print("Button pressed is:", i.text())
        pass

    def format_area(self, area):
        strnum = str(area)
        left = strnum[:strnum.find('.')]
        right = strnum[strnum.find('.'):]

        keep = count = len(left)
        fin = ''
        for i in left:
            if count % 3 == 0 and count != 0 and count != keep:
                fin += ', '
            fin += i
            count -= 1
        right += ' Meters'
        fin += right
        return fin

    def selection(self):
        try:
            connection = psycopg2.connect(user='postgres', password='12345678', host='localhost', port='5432',
                                      database='zomba_malawi')
            cursor = connection.cursor()
            query = """select fname, lname, plot_name, st_area(geom) area from developer Dv, plot Pl where Dv.plot_no = Pl.plot_no;"""
            cursor.execute(query)

            for c in cursor:
                print(c)
        except(Exception, psycopg2.Error) as error:
            if (connection):
                print('faileed to connect', error)
        finally:
            '''closing database connection'''
            if (connection):
                     cursor.close()
                     connection.close()
                     print("psql is closed")

    def handle_login(self):
        print('logging in')
        self.dlg.setCentralWidget(self.matabu)

    def connection(self):
        connection = psycopg2.connect(user='postgres', password='12345678', host='localhost', port='5432',
                                      database='zomba_malawi')
        return connection

    def available_plot_numbers(self):
        connection = self.connection()
        cursor = connection.cursor()
        query = """SELECT plot_no, plot_name FROM plot"""
        cursor.execute(query)
        for i in cursor:
            print(i[1])
            self.matabu.plot_combo.addItem(str(i[0])+"      "+i[1])

    def developers(self):
        try:
            connection = self.connection()
            cursor = connection.cursor()
            query = """select fname, lname, plot_name, st_area(geom), date_offered area from developer Dv, plot Pl where Dv.plot_no = Pl.plot_no;"""
            cursor.execute(query)
            for c in cursor:
                self.viewDevelopersDetails(c)

        except(Exception, psycopg2.Error) as error:
            if (connection):
                print('faileed to connect', error)
        finally:
            '''closing database connection'''
            if (connection):
                     cursor.close()
                     connection.close()
                     print("psql is closed")

    def viewDevelopersDetails(self,rowFromQuery):
        self.customeUi = CustomeUI()
        self.customeUi.iconLabel.setPixmap(QtGui.QPixmap("user1.png"))
        self.customeUi.developer.setText(rowFromQuery[0] + " " + rowFromQuery[1])
        self.customeUi.landdetails.setText(rowFromQuery[2] + " that occupy " + str(rowFromQuery[3]) + " km2")
        self.customeUi.date_offered.setText("Granted on " + str(rowFromQuery[4]))
        myQListWidgetItem = QListWidgetItem(self.matabu.developerslistwidget)
        myQListWidgetItem.setSizeHint(self.customeUi.sizeHint())
        self.matabu.developerslistwidget.addItem(myQListWidgetItem)
        self.matabu.developerslistwidget.setItemWidget(myQListWidgetItem, self.customeUi)




