# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Zomba
                                 A QGIS plugin
 zombaland management system
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-05-04
        git sha              : $Format:%H$
        copyright            : (C) 2019 by chanco
        email                : madamiss@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from qgis.core import QgsProject as qp, QgsFeature as qf, QgsFeatureRequest
from qgis.utils import iface
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QMessageBox
from PyQt5.QtSql import *


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .zomba_module_dialog import ZombaDialog
import os.path


class Zomba:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'Zomba_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Zomba_LMS')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('Zomba', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/zomba_module/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Files'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Zomba_LMS'),
                action)
            self.iface.removeToolBarIcon(action)

    def run(self):
        """Run method that performs all the real work"""
        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ZombaDialog()
        # qp is the QsgProject name
        # self.dlg.mainLeftList.clear()
        # self.dlg.mainLeftList.addItems(feature['name'] for feature in self.features)#[f['name'] for f in layer.getFeatures()])
        self.dlg.mainLeftList.itemSelectionChanged.connect(self.selectionChanged)
        self.dlg.filterList.textChanged.connect(self.filterListOnType)
        # self.dlg.selectedFeature.setText("Ndangoyambapo apapa")
        # self.dlg.viewDetailsBtn.clicked.connect(self.getSelectedFeature)
        # show the dialog
        self.dlg.add_btn.clicked.connect(self.add_btn_handler)
        self.database = self.connectToDb()
        query = '''select * from airports;'''
        recordList = self.executeQuery(self.database, query)
        self.populateLeftList(recordList)

        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

    def selectionChanged(self):
        self.getSelectedFeature()
        self.filterListOnType()

    def getSelectedFeature(self):
        row = self.dlg.mainLeftList.currentRow()
        item = self.dlg.mainLeftList.item(row)
        # #dir(item)
        # #self.dlg.textEdit.append(str(dir(item)))
        self.dlg.selectedFeature.setText(item.text())
        self.getAllFieldsFiltered(item.text())
        # self.fromAttributesTable(row)

    # def fromAttributesTable(self,fid):
    #     iterator = self.iface.activeLayer().getFeatures(QgsFeatureRequest().setFilterFid(fid))
    #     feat = next(iterator)
    #     attr = feat.attributes()
    #
    #     mylayer = iface.activeLayer()
    #     fields = mylayer.pendingFields
    #     field_names = [field.name() for field in fields]
    #     i = 0
    #     for att in attr:
    #         self.dlg.textEdit.append(field_names[i]+"   \r")
    #         self.dlg.textEdit.append(att)
    #         i += 1
    #
    #     self.dlg.textEdit.append(attr[1])
    #     self.dlg.textEdit.append(attr[2])

    def setAttributesOnFeatures(self, name):
        for f in self.features:
            if name == f[name]:
                print(str(dir(f)))
                break

    def connectToDb(self):
        db = QSqlDatabase('QPSQL')
        if db.isValid():
            db.setHostName('localhost')
            db.setDatabaseName('Zomba_db')
            db.setUserName('postgres')
            db.setPassword('12345678')
            db.setPort(5432)
            print('connected')
        else:
            print('failed to connect')
        return db

    def executeQuery(self,dbase,query):
        recordList = []
        if dbase.open():
            myQuery = dbase.exec_(query)
            while myQuery.next():
                recordList.append(myQuery.record())
        return recordList

    def populateLeftList(self, records):
        self.dlg.mainLeftList.addItems(x.value(5) for x in records)

    def getAllFieldsFiltered(self, name):
        query = """SELECT * FROM airports WHERE name = """ +"'"+ self.addQuote(name)+"';"
        after = self.executeQuery(self.database,query)[0]
        print(after.value("name_en"))
        self.dlg.wikipedia.setText(after.value("wikipedia"))
        self.dlg.name_en.setText(after.value("name_en"))
        self.dlg.name_es.setText(after.value("name_es"))
        self.dlg.geom.setText(after.value("geom"))
        self.dlg.gps_code.setText(after.value("gps_code"))


    def addQuote(self, name):
        if name.find("'")>=0:
            return name[:name.find("'")]+"'"+name[name.find("'"):]
        return name

    def filterListOnType(self):
        filter_text =  self.dlg.filterList.text().lower()
        #row = self.dlg.mainLeftList.currentRow()
        for it in range(self.dlg.mainLeftList.count()):
            item = self.dlg.mainLeftList.item(it)
            if filter_text in item.text().lower():
                self.dlg.mainLeftList.setRowHidden(it, False)
            else:
                self.dlg.mainLeftList.setRowHidden(it, True)

    def add_btn_handler(self):
        pn = self.dlg.pn.text()
        fname = self.dlg.fname.text()
        lname = self.dlg.lname.text()
        amt = self.dlg.amount.text()

        query_str = """INSERT INTO developer(plot,fname,lname,amount) VALUES('"""+pn+"','"+fname+"','"+lname+"',"+amt+");"
        print(query_str)

        if self.insertQuery(self.database,query_str):
            self.showdialog("Successfully added")
        else:
            self.showdialog("Developer not added review the details")

    def insertQuery(self,dbase,query):
        if dbase.open():
            myQuery = dbase.exec_(query)
            return True
        else:
            return False

    def showdialog(self,feedback):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)

        msg.setText(feedback)
        msg.setInformativeText(" ")
        msg.setWindowTitle("Add dev")
        msg.setDetailedText("")
        msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
        #msg.buttonClicked.connect(self.msgbtn)

        retval = msg.exec_()
        print("value of pressed message box button:", retval)

    def msgbtn(i):
        #print("Button pressed is:", i.text())
        pass




